[transaction]
prefix="5GPI"


[date]
format="2006-01-02 15:04:05.00"

[thread]
count=5

[queue]
user="guest"
password="guest"
address="localhost"
port=5672
[queue.exchange]
name="IncomingExchange"


[service]
prefix="/smsapi/pages/"

[db]
driver="mysql"
name="SMS_API_V2"
user="root"
password="1rstwap"
port=3306
address="127.0.0.1"
